name: 'app'

type: 'java:8'

hooks:
    build: |
        set -e
        cd jahia-module
        mvn clean install

relationships:
    database: 'mysqldb:mysql'
    jahia: 'jahia:http'

web:
    upstream:
        socket_family: tcp
        protocol: http
    commands:
        start: "sleep 60"
    locations:
        /:
            passthru: true

disk: 512

.counter: 1
