jahia:
    type: "jahia:7.2-rc"
    disk: 2048
    configuration:
        config: !archive jahia
    relationships:
        database: mysqldb:mysql

mysqldb:
    type: "mysql:10.2-rc"
    disk: 2048
    configuration:
        properties:
            max_allowed_packet: 100
